stages:
    - build
    - release

build:
    image: registry.gitlab.com/bradl/avr-gcc:latest
    stage: build
    script:
        - make _build/mines.hex
    artifacts:
        paths:
        - _build/mines.hex
    
release:
    image: registry.gitlab.com/gitlab-org/release-cli:latest
    stage: release
    script:
        - curl -o ./mines.hex -H "PRIVATE-TOKEN:$TOKEN" https://git.soton.ac.uk/api/v4/projects/$VUE_PROJECT_ID/jobs/artifacts/$BRANCH/raw/mines.hex?job=build
        - release-cli --server-url https://git.soton.ac.uk create --name="Continuous"