stages:
    - build
    - release

build:
    image: registry.gitlab.com/bradl/avr-gcc:latest
    stage: build
    script:
        - make _build/mines.hex
    artifacts:
        paths:
        - _build/mines.hex
    
release:
    image: registry.gitlab.com/gitlab-org/release-cli:latest
    stage: release
    script:
        - echo "ID ${CI_PROJECT_ID}"
        - echo "BRANCH ${CI_COMMIT_BRANCH}"
        - wget -O ./mines.hex --header "PRIVATE-TOKEN:$TOKEN" https://git.soton.ac.uk/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/$CI_COMMIT_BRANCH/raw/mines.hex?job=build
        - release-cli --server-url https://git.soton.ac.uk create --name="Continuous"